name: Publish to GitHub Wiki
on:
  # push:
  #   branches:
  #     - master
  #   paths:
  #     - wiki/**
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'stride3d/stride-website'
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - name: Upload Wiki pages
       uses: docker://decathlon/wiki-page-creator-action:2.0.1
       env:
         GH_PAT: ${{ secrets.GH_PAT }}
         ACTION_MAIL: github-bot@stride3d.net
         ACTION_NAME: VaclavElias
         OWNER: stride3d
         REPO_NAME: stride-website
         MD_FOLDER: wiki